### ISSUE TITLE
Question for your paper

### ISSUE THREAD

**Issue by Fangwq** [duvenaud/deep-limits#1]
Hi, I am reading your Phd thesis recently. I am a little confused about the Equation 5.11 in the chapter 5. Can you give me any clue or references to deduce the equation ? Thank you very much.

**Comment by duvenaud** [comment]
Good question.  I think I just wrote out the definition of variance as an integral, plugged in the density of a half-Gaussian, and let symbolic integration software do the rest :)

**Comment by Fangwq** [comment]
OK, I see where I went wrong. Thank you very much!
